### ISSUE TITLE
Parental rating tests should not use hasOwnProperty to check 

### ISSUE THREAD

**Issue by fvalleeHbbTV** [mitxp/HbbTV-Testsuite#42] opened 2017-05-31 13:41 UTC
```
Parental ratings tests are using hasOwnProperty to check if "name" and "value" are set on the ParentalRating object.

http://itv.mit-xperts.com/hbbtvtest/parentalcontrol/index.html line 90:

> if (!rating.hasOwnProperty('name') || !rating.hasOwnProperty('value')) { 

This test is incorrect, as the properties name & values have no reason to be "own properties" as they are defined on the object prototype.
Please check using 
if ('name' in rating) 
I guess you could also check using 
rating.prototype.hasOwnProperty('name')

https://stackoverflow.com/questions/13632999/if-key-in-object-or-ifobject-hasownpropertykey
https://developers.google.com/web/updates/2015/04/DOM-attributes-now-on-the-prototype-chain

**Comment by mitxp** [comment] 2017-05-31 15:17
Could you please verify that the issue is fixed on itv.mit-xperts.com (not checked in yet).

**Comment by fvalleeHbbTV** [comment] 2017-05-31 15:19
Yes, it seems fixed now ! thanks a lot !

**Closed** 2017-05-31 15:20 UTC
